version: '3.2'
services:
  api:
    build: .
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    depends_on:
      - store
    command: ["./wait-for-it.bash", "store:6379", "--", "/api"]
  store:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
