FROM redis:4.0-alpine
MAINTAINER Charles Paulet <charles.paulet@epitech.eu>

ENV REDIS_PASSWORD foobar
#COPY ./redis-prod.conf /usr/local/etc/redis/redis.conf

CMD ["sh", "-c", "exec redis-server --requirepass \"$REDIS_PASSWORD\""]
#CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
